# In termainal:
# $ kubectl apply -f storageClass.yml
# Running order:
# 1. storageClass.yml
# 2. pv.yml
# 3. service.yml
# 4. queue.yml

# For some reason the RabbitMQ queue was restarting and i couldn't find any
# information in the logs why it was restarting. And because of that restart,
# lot of the reservices aren't working. So services that needed to publish a
# message to another service, probably at the point of publishing a message, the
# queue would restart and then the data would not be saved in the database.
# SO that was a huge problem because the queue just kept restarting.
# To resolve that experience where queue just keeps restarting, like it runs
# for 10 or 20 minutes and then restarts, i came with an approach to update
# the queue so that i have the queue that doesn't restart.
# And I decided to update by setting up Persistent Volume, Persistent Volume
# Claim and Storage Class. Before it was just Deployment and Service. I think
# the reason why it was restarting is because of no storage attached to it.
# So I tested by setting up a Persistent Volume, Persistent Volume Claim and
# Storage Class. And it seems to be working fine.
# In a nutshell, I created Persistent Volume, Persistent Volume Claim and
# Storage Class and then use it in the Deployment file.

# @ Storage Class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
